//  ---------- INLCUDED BLOCK: onetotwo  ---------- 
module onetotwo(in, out1, out2);
  input in;
  output out1, out2;
  wire i1, i2;
  assign i1 = !in;
  assign i2 = !in;
  assign out1 = !i1;
  assign out2 = !i2;
endmodule



//  ---------- INLCUDED BLOCK: fifo_core  ---------- 
// Fixed size: 8 locations, 16-bit data width.
module fifo_core (
    input                       clk,
    input                       rst_n,
    input                       wr_en,
    input                       rd_en,
    input      [15:0]           din,
    input                       full,
    input                       empty,
    
    output reg [15:0]           dout,
    output reg [2:0]            wptr,
    output reg [2:0]            rptr
);

    // Memory is fixed to 8 locations of 16 bits each.
  reg [15:0] fifo[7:0];

    // Write logic: updates the write pointer and writes to memory
    always @(posedge clk) begin
      if (!rst_n) begin
            wptr <= 0;
        end else if (wr_en & !full) begin
            fifo[wptr] <= din;
            wptr <= wptr + 1;
        end
    end

    // Read logic: updates the read pointer and reads from memory
    always @(posedge clk) begin
      if (!rst_n) begin
            rptr <= 0;
        end else if (rd_en & !empty) begin
            dout <= fifo[rptr];
            rptr <= rptr + 1;
        end
    end

endmodule



//  ---------- INLCUDED BLOCK: fifo_status  ---------- 
// Block 2: Status Generation Logic (Full/Empty)
// Fixed for 3-bit pointers (depth of 8).
module fifo_status (
    input [2:0]                 wptr,
    input [2:0]                 rptr,
    output                      full,
    output                      empty
);

  assign full  = (wptr + 3'b1) == rptr;
  assign empty = wptr == rptr;

endmodule


// Automatically generated by ChipInventor Cloud EDA Tool - 3.15
// Careful: this file (hdl.v) will be automatically replaced
// when you ask tool to generate top Verilog code by clicking
// at BLOCKS button.

module top (

  input wire clk,
  input wire rst_n,
  input wire wr_en,
  input wire rd_en,
  input wire [15:0] din,
  output wire [15:0] dout,
  output wire empty,
  output wire full

);

//Internal Wires
 wire w_1;
 wire w_2;
 wire [2:0] w_3;
 wire [2:0] w_4;
 wire w_5;
 wire w_6;

//Instances of Modules
fifo_core blk1885_1 (
         .clk (clk),
         .rst_n (rst_n),
         .wr_en (wr_en),
         .rd_en (rd_en),
         .din (din[15:0]),
         .dout (dout[15:0]),
         .full (w_1),
         .empty (w_2),
         .wptr (w_3),
         .rptr (w_4)
     );

fifo_status blk1886_7 (
         .wptr (w_3),
         .rptr (w_4),
         .full (w_5),
         .empty (w_6)
     );

onetotwo blk92_8 (
         .out1 (full),
         .out2 (w_1),
         .in (w_5)
     );

onetotwo blk92_9 (
         .out1 (empty),
         .out2 (w_2),
         .in (w_6)
     );


endmodule
